import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import News from "@/components/News";
import SessionWrapper from "@/components/SessionProvider";
import CommentModal from "@/components/CommentModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = 'force-dynamic';

export default function RootLayout({ children }) {
  return (
    <SessionWrapper>
    <html lang="en">
      <body className={inter.className}>
        
        <div className='flex justify-between max-w-6xl mx-auto'>
          {/* to see it all the way down the h-screen */}
          <div className='hidden sm:inline border-r h-screen sticky top-0'> 
            <Sidebar/>
          </div>

{/* In Tailwind CSS, flex-1 is a class that allows a flex item to grow and shrink while ignoring its initial size */}
        <div className='flex-1'>
        {children}
        </div>

        <div className="lg:flex-col p-3 h-screen border-l hidden lg:flex w-[24rem]">
          <div className='sticky top-0 bg-white py-2'>
          <input type='text' placeholder="search" className='bg-gray-100 border border-gray-200 rounded-3xl text-sm w-full px-4 py-2' />
          </div>
          <News />
        </div>
        </div>
        <CommentModal />
        </body>
    </html>
    </SessionWrapper>
  );
}
// hello im back
